apiVersion: v1
kind: Service
metadata:
  name: paulojauregui-com
  namespace: websites
spec:
  selector:
    app: paulojauregui-com
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
