name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/howdiggy/paulojauregui-com:latest
            ghcr.io/${{ github.repository_owner | lowercase }}/paulojauregui-com:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update deployment manifest
        if: github.event_name != 'pull_request'
        run: |
          echo "Updating image tag in GitOps repository"
          git clone https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/HowDiggy/k8s-gitops.git
          cd k8s-gitops
          
          # Ensure the directory exists
          mkdir -p websites/paulojauregui-com
          
          # Update the deployment.yaml with the new image tag
          if [ -f websites/paulojauregui-com/deployment.yaml ]; then
            sed -i "s|image: ghcr.io/${{ github.repository_owner | lowercase }}/paulojauregui-com:.*|image: ghcr.io/${{ github.repository_owner | lowercase }}/paulojauregui-com:${{ github.sha }}|g" websites/paulojauregui-com/deployment.yaml
          else
            # Copy files from template directory if available
            echo "Creating deployment files..."
            cp -r ../k8s-templates/* websites/paulojauregui-com/ 2>/dev/null || true
            
            # If templates not available, create files manually
            if [ ! -f websites/paulojauregui-com/deployment.yaml ]; then
              # Create basic files
              echo "Creating basic Kubernetes manifests"
              # Files will be created by following steps
            fi
            
            # Update the image tag in the newly created deployment file
            if [ -f websites/paulojauregui-com/deployment.yaml ]; then
              sed -i "s|image: ghcr.io/${{ github.repository_owner | lowercase }}/paulojauregui-com:.*|image: ghcr.io/${{ github.repository_owner | lowercase }}/paulojauregui-com:${{ github.sha }}|g" websites/paulojauregui-com/deployment.yaml
            fi
          fi
          
          # Set up git config
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Commit and push changes
          git add websites/paulojauregui-com/
          git commit -m "Update paulojauregui-com image to ${{ github.sha }}" || echo "No changes to commit"
          git push
